# Azure Developer CLI configuration file
# Learn more about azd here: https://aka.ms/azd
# Learn more about configuring azd for your project: https://aka.ms/azure-dev-yaml

name: esg-reporting
metadata:
  template: esg-reporting-solution@1.0.0

# Infrastructure configuration
infra:
  provider: bicep
  path: infra

# Resource group configuration
resourceGroup: rg-${AZURE_ENV_NAME}

# Services configuration
services:
  esg-reporting:
    project: .
    language: python
    host: containerapp

# Pipeline configuration
pipeline:
  provider: github

# Hooks for deployment lifecycle
hooks:
  postdeploy:
    shell: pwsh
    run: |
      Write-Host "Setting up environment configuration..."
      if (Test-Path ".env.example") {
        if (-not (Test-Path ".env")) {
          Copy-Item ".env.example" ".env"
          Write-Host "Created .env file from template. Please update with your values."
        }
      }
      Write-Host "Installing Python dependencies..."
      try {
        pip install -r requirements.txt
        pip install -e .
        pip install pytest  # Ensure pytest is available
        Write-Host "Running tests to verify installation..."
        pytest tests/ -v
        Write-Host "ESG Reporting deployment complete!"
        Write-Host "Run 'esg-reporting --help' to get started."
      }
      catch {
        Write-Host "Warning: Some installation steps failed, but deployment may still be functional."
        Write-Host "Error details: $($_.Exception.Message)"
        Write-Host "You can manually install dependencies with: pip install -r requirements.txt && pip install -e ."
      }
